[package]
name = "rten-mobilenet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.8"
ndarray = "0.15.6"
rten = "0.3.0"
rten-tensor = "0.3.0"
serde_json = "1.0.111"
